/**
 * 定义应用路由
 */
import 'babel-polyfill';
import React from 'react';
import * as ReactRouterDOM from '../lib/react-router-dom';

// import {
//   Router,
//   // browserHistory,
//   hashHistory,
// } from 'react-router';

// 路由配置规则参考： https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#configuration-with-plain-routes
// 一下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
import HeaderAsideFooterLayout from '../layouts/HeaderAsideFooterLayout';
import UserLayout from '../layouts/UserLayout';

import Home from '../pages/Home';
import Login from '../pages/Login';
import NotFound from '../pages/NotFound';

// user page
import Activity from '../pages/Activity';

console.log(ReactRouterDOM);

const {
  BrowserRouter: Router,
  Route,
} = ReactRouterDOM;

const autoGeneratedRoutes = [{
  path: '/',
  exact: true,
  childRoutes: [{
    path: '*',
    childRoutes: [],
    component: NotFound,
  }],
  component: HeaderAsideFooterLayout,
  indexRoute: {
    component: Home,
  },
}, {
  path: '/activity',
  childRoutes: [{
    path: '*',
    childRoutes: [],
    component: NotFound,
  }],
  component: HeaderAsideFooterLayout,
  indexRoute: {
    component: Activity,
  },
}];
// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

const routes = [...autoGeneratedRoutes, ...customRoutes];

// wrap <Route> and use this everywhere instead, then when
// sub routes are added to any route it'll work
const RouteWithSubRoutes = route => {
  return (
    <Route
      path={route.path}
      exact={route.exact}
      render={props => (
        // pass the sub-routes down to keep nesting
        <route.component {...props} route={route} />
      )}
    />
  );
};

export default (
  <Router>
    <div>
      {routes.map(RouteWithSubRoutes)}
    </div>
  </Router>
);
